# Generated by Django 4.0.6 on 2022-07-19 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
